Task 1 — Unit Converter

In [1]:
def convert_units():
    """
    Converts different units of measurement.

    Conversion Types:
    1. Length (meters ↔ feet)
    2. Weight (kilograms ↔ pounds)
    3. Volume (liters ↔ gallons)

    Returns:
        float: converted value depending on user selection
    """

    print("Select conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choice = input("Enter choice (1/2/3): ")

    try:
        value = float(input("Enter value to convert: "))

        if choice == "1":
            print("1. meters → feet")
            print("2. feet → meters")
            sub = input("Choose conversion: ")

            if sub == "1":
                result = value * 3.28084
                print(f"{value} meters = {result} feet")

            elif sub == "2":
                result = value / 3.28084
                print(f"{value} feet = {result} meters")

            else:
                print("Invalid length option")

        elif choice == "2":
            print("1. kg → pounds")
            print("2. pounds → kg")
            sub = input("Choose conversion: ")

            if sub == "1":
                result = value * 2.20462
                print(f"{value} kg = {result} pounds")

            elif sub == "2":
                result = value / 2.20462
                print(f"{value} pounds = {result} kg")

            else:
                print("Invalid weight option")

        elif choice == "3":
            print("1. liters → gallons")
            print("2. gallons → liters")
            sub = input("Choose conversion: ")

            if sub == "1":
                result = value * 0.264172
                print(f"{value} liters = {result} gallons")

            elif sub == "2":
                result = value / 0.264172
                print(f"{value} gallons = {result} liters")

            else:
                print("Invalid volume option")

        else:
            print("Invalid conversion type")

    except ValueError:
        print("Invalid input! Please enter a numeric value.")


convert_units()

Select conversion type:
1. Length
2. Weight
3. Volume
Enter choice (1/2/3): 2
Enter value to convert: 60
1. kg → pounds
2. pounds → kg
Choose conversion: 2
60.0 pounds = 27.215574566138386 kg


Task 2 — Mathematical Operations on List

In [3]:
def calculate_sum(numbers):
    """
    Returns the sum of a list of numbers.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: sum of numbers
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Returns the average of a list of numbers.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: average value
    """
    return sum(numbers) / len(numbers)


def find_max(numbers):
    """
    Returns the maximum value in a list.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: maximum value
    """
    return max(numbers)


def find_min(numbers):
    """
    Returns the minimum value in a list.

    Parameters:
    numbers (list): list of numeric values

    Returns:
    float: minimum value
    """
    return min(numbers)


def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1-4): ")

    try:
        numbers = input("Enter numbers separated by space: ")
        numbers_list = [float(num) for num in numbers.split()]

        if len(numbers_list) == 0:
            print("List cannot be empty")
            return

        if choice == "1":
            print("Sum =", calculate_sum(numbers_list))

        elif choice == "2":
            print("Average =", calculate_average(numbers_list))

        elif choice == "3":
            print("Maximum =", find_max(numbers_list))

        elif choice == "4":
            print("Minimum =", find_min(numbers_list))

        else:
            print("Invalid operation selected")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")


main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 1
Enter numbers separated by space: 12 16 18 150
Sum = 196.0


4.2 Exercise on List Manipulation
1 Extract Every Other Element

In [4]:
def extract_every_other(lst):
    return lst[::2]

print(extract_every_other([1,2,3,4,5,6]))

[1, 3, 5]


2 Slice a Sublist

In [5]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

print(get_sublist([1,2,3,4,5,6],2,4))

[3, 4, 5]


3 Reverse List Using Slicing

In [6]:
def reverse_list(lst):
    return lst[::-1]

print(reverse_list([1,2,3,4,5]))

[5, 4, 3, 2, 1]


4 Remove First and Last Elements

In [7]:
def remove_first_last(lst):
    return lst[1:-1]

print(remove_first_last([1,2,3,4,5]))

[2, 3, 4]


5 Get First n Elements

In [8]:
def get_first_n(lst, n):
    return lst[:n]

print(get_first_n([1,2,3,4,5],3))

[1, 2, 3]


6 Get Last n Elements

In [9]:
def get_last_n(lst, n):
    return lst[-n:]

print(get_last_n([1,2,3,4,5],2))

[4, 5]


7 Reverse Skip Elements

In [10]:
def reverse_skip(lst):
    return lst[-2::-2]

print(reverse_skip([1,2,3,4,5,6]))

[5, 3, 1]


4.3 Exercise on Nested List
1 Flatten Nested List

In [11]:
def flatten(lst):
    result = []
    for sub in lst:
        for item in sub:
            result.append(item)
    return result

print(flatten([[1,2],[3,4],[5]]))

[1, 2, 3, 4, 5]


2 Access Nested Element

In [12]:
def access_nested_element(lst, indices):
    element = lst
    for i in indices:
        element = element[i]
    return element

lst = [[1,2,3],[4,5,6],[7,8,9]]
print(access_nested_element(lst,[1,2]))

6


3 Sum of Nested List

In [13]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item,list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1,2],[3,[4,5]],6]))

21


4 Remove Element from Nested List

In [14]:
def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.append(remove_element(item,elem))
        elif item != elem:
            result.append(item)
    return result

print(remove_element([[1,2],[3,2],[4,5]],2))

[[1], [3], [4, 5]]


5 Find Maximum Element

In [15]:
def find_max(lst):
    maximum = float('-inf')

    for item in lst:
        if isinstance(item,list):
            maximum = max(maximum, find_max(item))
        else:
            maximum = max(maximum,item)

    return maximum

print(find_max([[1,2],[3,[4,5]],6]))

6


6 Count Occurrences

In [16]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item,list):
            count += count_occurrences(item,elem)
        elif item == elem:
            count += 1
    return count

print(count_occurrences([[1,2],[2,3],[2,4]],2))

3


7 Deep Flatten

In [17]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item,list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))

[1, 2, 3, 4, 5, 6, 7, 8]


8 Nested List Average

In [18]:
def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat)/len(flat)

print(average_nested([[1,2],[3,4],[5,6]]))

3.5


10.1 Basic Vector and Matrix Operations with NumPy

In [19]:
import numpy as np

Problem 1 — Array Creation

In [20]:
# 1 Initialize empty array 2x2
a = np.empty((2,2))
print("Empty array:\n", a)

# 2 Initialize ones array 4x2
b = np.ones((4,2))
print("Ones array:\n", b)

# 3 Array filled with specific value
c = np.full((3,3), 7)
print("Full array:\n", c)

# 4 Zeros array like existing array
d = np.zeros_like(c)
print("Zeros like array:\n", d)

# 5 Ones array like existing array
e = np.ones_like(c)
print("Ones like array:\n", e)

# 6 Convert list to numpy array
new_list = [1,2,3,4]
f = np.array(new_list)
print("Converted array:", f)

Empty array:
 [[2.41087731e-315 0.00000000e+000]
 [1.86919106e-306 1.69121367e-306]]
Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full array:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
Zeros like array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Ones like array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Converted array: [1 2 3 4]


Problem 2 — Array Manipulation

In [21]:
# 1 Array from 10 to 49
arr1 = np.arange(10,50)
print(arr1)

# 2 3x3 matrix 0-8
arr2 = np.arange(9).reshape(3,3)
print(arr2)

# 3 Identity matrix
arr3 = np.eye(3)
print(arr3)

# 4 Random array size 30 and mean
arr4 = np.random.random(30)
print("Mean:", arr4.mean())

# 5 Random 10x10 matrix min and max
arr5 = np.random.random((10,10))
print("Min:", arr5.min())
print("Max:", arr5.max())

# 6 Zero array size 10 replace 5th element
arr6 = np.zeros(10)
arr6[4] = 1
print(arr6)

# 7 Reverse array
arr7 = np.array([1,2,0,0,4,0])
print(arr7[::-1])

# 8 2D array border 1 inside 0
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0
print(arr8)

# 9 Checkerboard 8x8
arr9 = np.zeros((8,8),dtype=int)
arr9[1::2,::2] = 1
arr9[::2,1::2] = 1
print(arr9)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Mean: 0.4474675293862306
Min: 0.01330352208268415
Max: 0.9848168363512952
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0 4 0 0 2 1]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3 — Array Operations

In [23]:
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

# 1 Add arrays
print(x + y)

# 2 Subtract arrays
print(x - y)

# 3 Multiply with integer
print(x * 2)

# 4 Square each element
print(np.square(x))

# 5 Dot products
print("v dot w =", np.dot(v,w))
print("x dot v =", np.dot(x,v))
print("x dot y =\n", np.dot(x,y))

# 6 Concatenate
print(np.concatenate((x,y),axis=0))  # row
print(np.vstack((v,w)))  # column

# 7 Concatenate x and v
print(np.vstack((x, v)))

[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 2  4]
 [ 6 10]]
[[ 1  4]
 [ 9 25]]
v dot w = 219
x dot v = [29 77]
x dot y =
 [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]
[[ 1  2]
 [ 3  5]
 [ 9 10]]


Problem 4 — Matrix Operations

In [24]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1 Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
print("A * A^-1 =\n", np.dot(A,A_inv))

# 2 Prove AB ≠ BA
print("AB =\n", np.dot(A,B))
print("BA =\n", np.dot(B,A))

# 3 Prove (AB)^T = B^T A^T
left = np.transpose(np.dot(A,B))
right = np.dot(np.transpose(B), np.transpose(A))

print("Left:\n", left)
print("Right:\n", right)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
Left:
 [[23 51]
 [13 29]]
Right:
 [[23 51]
 [13 29]]


Solve Linear Equations

In [25]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])

B = np.array([-1,-3,9])

# Solve AX = B
A_inv = np.linalg.inv(A)
X = np.dot(A_inv,B)

print("Solution:", X)

Solution: [ 2.  1. -2.]


In [26]:
X = np.linalg.solve(A,B)
print("Solution using linalg.solve:", X)

Solution using linalg.solve: [ 2.  1. -2.]


10.2 Experiment — How Fast is NumPy
1 Element-wise Addition

Python Lists

In [28]:
import time

size = 1000000

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [list1[i] + list2[i] for i in range(size)]

end = time.time()

print("Python list addition time:", end-start)

Python list addition time: 0.11095070838928223


NumPy Arrays

In [29]:
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()

result = arr1 + arr2

end = time.time()

print("NumPy addition time:", end-start)

NumPy addition time: 0.08476996421813965


2 Element-wise Multiplication

Python

In [30]:
start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python multiplication time:", end-start)

Python multiplication time: 0.11017751693725586


NumPy

In [31]:
start = time.time()

result = arr1 * arr2

end = time.time()

print("NumPy multiplication time:", end-start)

NumPy multiplication time: 0.0172271728515625


2 Element-wise Multiplication

Python

In [32]:
start = time.time()

result = [list1[i] * list2[i] for i in range(size)]

end = time.time()

print("Python multiplication time:", end-start)

Python multiplication time: 0.11643576622009277


NumPy

In [33]:
start = time.time()

result = arr1 * arr2

end = time.time()

print("NumPy multiplication time:", end-start)

NumPy multiplication time: 0.016704797744750977


3 Dot Product

Python

In [34]:
start = time.time()

dot = sum(list1[i]*list2[i] for i in range(size))

end = time.time()

print("Python dot product time:", end-start)

Python dot product time: 0.11045360565185547


NumPy

In [35]:
start = time.time()

dot = np.dot(arr1,arr2)

end = time.time()

print("NumPy dot product time:", end-start)

NumPy dot product time: 0.0023276805877685547


4 Matrix Multiplication
Python Lists

In [36]:
import random

size = 100

A = [[random.random() for _ in range(size)] for _ in range(size)]
B = [[random.random() for _ in range(size)] for _ in range(size)]

start = time.time()

result = [[sum(A[i][k]*B[k][j] for k in range(size))
          for j in range(size)]
          for i in range(size)]

end = time.time()

print("Python matrix multiplication time:", end-start)

Python matrix multiplication time: 0.10110664367675781


NumPy

In [37]:
A = np.random.random((100,100))
B = np.random.random((100,100))

start = time.time()

result = np.dot(A,B)

end = time.time()

print("NumPy matrix multiplication time:", end-start)

NumPy matrix multiplication time: 0.004438638687133789
